### ISSUE TITLE
The problem with the requirement.txt

### ISSUE THREAD

**Issue by sylph520** [Beliefuture/Index_EAB#1]
I tried to set up the project, but received many errors when setting up the virtual environment at the first step. I found that the current requirements.txt file contains multiple packages without specified versions and references local directories? Would you please update it? Thanks.

**Comment by Beliefuture** [comment]
> I tried to set up the project, but received many errors when setting up the virtual environment at the first step. I found that the current requirements.txt file contains multiple packages without specified versions and references local directories? Would you please update it? Thanks.

 @sylph520 Thanks for your interests in our work. 

Could I ask if you can provide more details about the errors occurred? The file `requirement.txt` was generated automatically by exporting all the packages in the environment. You can also try to set up a new python environment from the scratch and run the corresponding modules. In that way, the required but missing packages can be identified one by one and you can install them with the `pip` command.

**Comment by sylph520** [comment]
Okay, thanks

**Comment by kynecubus** [comment]
@sylph520 Hello. I'm currently in the process of setting up the environment as well. I was wondering if you have managed to solve this issue? If it's convenient for you, could you please share the requirements? Thank you very much. 

> I tried to set up the project, but received many errors when setting up the virtual environment at the first step. I found that the current requirements.txt file contains multiple packages without specified versions and references local directories? Would you please update it? Thanks.
