### ISSUE TITLE
tree model dataset

### ISSUE THREAD

**Issue by chenjifei111222** [Beliefuture/Index_EAB#2]
Can you please show me the dataset of the tree_model? for example /data/wz/index/index_eab/eab_benefit/tree_model/data/tpch/tree_tpch_cost_data_tgt_train.json

**Comment by chenjifei111222** [comment]
my email is   1751896300@qq.com

**Comment by Beliefuture** [comment]
> Can you please show me the dataset of the tree_model? for example /data/wz/index/index_eab/eab_benefit/tree_model/data/tpch/tree_tpch_cost_data_tgt_train.json

Thanks for your interest in our work. 

The dataset for one item is organized in the following format with the keys (`['sql', 'indexes', 'w/o estimated cost', 'w/ estimated cost', 'w/o actual cost', 'w/ actual cost', 'w/ 'w/ plan']`) and you can build you own dataset based on it:

```
[
     {
        "sql": "SELECT ps_availqty, s_suppkey FROM supplier JOIN partsupp ON ps_suppkey = s_suppkey WHERE ps_supplycost > 965.06 AND s_nationkey < 23 AND s_address <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc' AND s_phone <= '26-432-258-4986' ORDER BY ps_availqty ASC, s_suppkey ASC",
        "indexes": [
            "partsupp#ps_supplycost"
        ],
        "w/o estimated cost": 25177.87,
        "w/ estimated cost": 20897.31,
        "w/o actual cost": 48.185,
        "w/ actual cost": 207.022,
        "w/o plan": {
            "Node Type": "Gather Merge",
            "Parallel Aware": false,
            "Startup Cost": 23561.23,
            "Total Cost": 25177.87,
            "Plan Rows": 13856,
            "Plan Width": 8,
            "Workers Planned": 2,
            "Plans": [
                {
                    "Node Type": "Sort",
                    "Parent Relationship": "Outer",
                    "Parallel Aware": false,
                    "Startup Cost": 22561.2,
                    "Total Cost": 22578.52,
                    "Plan Rows": 6928,
                    "Plan Width": 8,
                    "Sort Key": [
                        "partsupp.ps_availqty",
                        "supplier.s_suppkey"
                    ],
                    "Plans": [
                        {
                            "Node Type": "Hash Join",
                            "Parent Relationship": "Outer",
                            "Parallel Aware": false,
                            "Join Type": "Inner",
                            "Startup Cost": 472.45,
                            "Total Cost": 22119.26,
                            "Plan Rows": 6928,
                            "Plan Width": 8,
                            "Inner Unique": true,
                            "Hash Cond": "(partsupp.ps_suppkey = supplier.s_suppkey)",
                            "Plans": [
                                {
                                    "Node Type": "Seq Scan",
                                    "Parent Relationship": "Outer",
                                    "Parallel Aware": true,
                                    "Relation Name": "partsupp",
                                    "Alias": "partsupp",
                                    "Startup Cost": 0,
                                    "Total Cost": 21616.67,
                                    "Plan Rows": 11478,
                                    "Plan Width": 8,
                                    "Filter": "(ps_supplycost > 965.06)"
                                },
                                {
                                    "Node Type": "Hash",
                                    "Parent Relationship": "Inner",
                                    "Parallel Aware": false,
                                    "Startup Cost": 397,
                                    "Total Cost": 397,
                                    "Plan Rows": 6036,
                                    "Plan Width": 4,
                                    "Plans": [
                                        {
                                            "Node Type": "Seq Scan",
                                            "Parent Relationship": "Outer",
                                            "Parallel Aware": false,
                                            "Relation Name": "supplier",
                                            "Alias": "supplier",
                                            "Startup Cost": 0,
                                            "Total Cost": 397,
                                            "Plan Rows": 6036,
                                            "Plan Width": 4,
                                            "Filter": "((s_nationkey < 23) AND ((s_address)::text <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc'::text) AND (s_phone <= '26-432-258-4986'::bpchar))"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "w/ plan": {
            "Node Type": "Sort",
            "Parallel Aware": false,
            "Startup Cost": 20855.75,
            "Total Cost": 20897.31,
            "Plan Rows": 16627,
            "Plan Width": 8,
            "Sort Key": [
                "partsupp.ps_availqty",
                "supplier.s_suppkey"
            ],
            "Plans": [
                {
                    "Node Type": "Hash Join",
                    "Parent Relationship": "Outer",
                    "Parallel Aware": false,
                    "Join Type": "Inner",
                    "Startup Cost": 1073.99,
                    "Total Cost": 19690.09,
                    "Plan Rows": 16627,
                    "Plan Width": 8,
                    "Inner Unique": true,
                    "Hash Cond": "(partsupp.ps_suppkey = supplier.s_suppkey)",
                    "Plans": [
                        {
                            "Node Type": "Bitmap Heap Scan",
                            "Parent Relationship": "Outer",
                            "Parallel Aware": false,
                            "Relation Name": "partsupp",
                            "Alias": "partsupp",
                            "Startup Cost": 601.54,
                            "Total Cost": 19145.3,
                            "Plan Rows": 27547,
                            "Plan Width": 8,
                            "Recheck Cond": "(ps_supplycost > 965.06)",
                            "Plans": [
                                {
                                    "Node Type": "Bitmap Index Scan",
                                    "Parent Relationship": "Outer",
                                    "Parallel Aware": false,
                                    "Index Name": "<13002>btree_partsupp_ps_supplycost",
                                    "Startup Cost": 0,
                                    "Total Cost": 594.65,
                                    "Plan Rows": 27547,
                                    "Plan Width": 0,
                                    "Index Cond": "(ps_supplycost > 965.06)"
                                }
                            ]
                        },
                        {
                            "Node Type": "Hash",
                            "Parent Relationship": "Inner",
                            "Parallel Aware": false,
                            "Startup Cost": 397,
                            "Total Cost": 397,
                            "Plan Rows": 6036,
                            "Plan Width": 4,
                            "Plans": [
                                {
                                    "Node Type": "Seq Scan",
                                    "Parent Relationship": "Outer",
                                    "Parallel Aware": false,
                                    "Relation Name": "supplier",
                                    "Alias": "supplier",
                                    "Startup Cost": 0,
                                    "Total Cost": 397,
                                    "Plan Rows": 6036,
                                    "Plan Width": 4,
                                    "Filter": "((s_nationkey < 23) AND ((s_address)::text <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc'::text) AND (s_phone <= '26-432-258-4986'::bpchar))"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    }
]
```

**Comment by chenjifei111222** [comment]
Thank you for your answer. Can you please send me the dataset you are using? What is the difference between w/o and w/here

> > Can you please show me the dataset of the tree_model? for example /data/wz/index/index_eab/eab_benefit/tree_model/data/tpch/tree_tpch_cost_data_tgt_train.json
> 
> Thanks for your interest in our work.
> 
> The dataset for one item is organized in the following format with the keys (`['sql', 'indexes', 'w/o estimated cost', 'w/ estimated cost', 'w/o actual cost', 'w/ actual cost', 'w/ 'w/ plan']`) and you can build you own dataset based on it:
> 
> ```
> [
>      {
>         "sql": "SELECT ps_availqty, s_suppkey FROM supplier JOIN partsupp ON ps_suppkey = s_suppkey WHERE ps_supplycost > 965.06 AND s_nationkey < 23 AND s_address <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc' AND s_phone <= '26-432-258-4986' ORDER BY ps_availqty ASC, s_suppkey ASC",
>         "indexes": [
>             "partsupp#ps_supplycost"
>         ],
>         "w/o estimated cost": 25177.87,
>         "w/ estimated cost": 20897.31,
>         "w/o actual cost": 48.185,
>         "w/ actual cost": 207.022,
>         "w/o plan": {
>             "Node Type": "Gather Merge",
>             "Parallel Aware": false,
>             "Startup Cost": 23561.23,
>             "Total Cost": 25177.87,
>             "Plan Rows": 13856,
>             "Plan Width": 8,
>             "Workers Planned": 2,
>             "Plans": [
>                 {
>                     "Node Type": "Sort",
>                     "Parent Relationship": "Outer",
>                     "Parallel Aware": false,
>                     "Startup Cost": 22561.2,
>                     "Total Cost": 22578.52,
>                     "Plan Rows": 6928,
>                     "Plan Width": 8,
>                     "Sort Key": [
>                         "partsupp.ps_availqty",
>                         "supplier.s_suppkey"
>                     ],
>                     "Plans": [
>                         {
>                             "Node Type": "Hash Join",
>                             "Parent Relationship": "Outer",
>                             "Parallel Aware": false,
>                             "Join Type": "Inner",
>                             "Startup Cost": 472.45,
>                             "Total Cost": 22119.26,
>                             "Plan Rows": 6928,
>                             "Plan Width": 8,
>                             "Inner Unique": true,
>                             "Hash Cond": "(partsupp.ps_suppkey = supplier.s_suppkey)",
>                             "Plans": [
>                                 {
>                                     "Node Type": "Seq Scan",
>                                     "Parent Relationship": "Outer",
>                                     "Parallel Aware": true,
>                                     "Relation Name": "partsupp",
>                                     "Alias": "partsupp",
>                                     "Startup Cost": 0,
>                                     "Total Cost": 21616.67,
>                                     "Plan Rows": 11478,
>                                     "Plan Width": 8,
>                                     "Filter": "(ps_supplycost > 965.06)"
>                                 },
>                                 {
>                                     "Node Type": "Hash",
>                                     "Parent Relationship": "Inner",
>                                     "Parallel Aware": false,
>                                     "Startup Cost": 397,
>                                     "Total Cost": 397,
>                                     "Plan Rows": 6036,
>                                     "Plan Width": 4,
>                                     "Plans": [
>                                         {
>                                             "Node Type": "Seq Scan",
>                                             "Parent Relationship": "Outer",
>                                             "Parallel Aware": false,
>                                             "Relation Name": "supplier",
>                                             "Alias": "supplier",
>                                             "Startup Cost": 0,
>                                             "Total Cost": 397,
>                                             "Plan Rows": 6036,
>                                             "Plan Width": 4,
>                                             "Filter": "((s_nationkey < 23) AND ((s_address)::text <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc'::text) AND (s_phone <= '26-432-258-4986'::bpchar))"
>                                         }
>                                     ]
>                                 }
>                             ]
>                         }
>                     ]
>                 }
>             ]
>         },
>         "w/ plan": {
>             "Node Type": "Sort",
>             "Parallel Aware": false,
>             "Startup Cost": 20855.75,
>             "Total Cost": 20897.31,
>             "Plan Rows": 16627,
>             "Plan Width": 8,
>             "Sort Key": [
>                 "partsupp.ps_availqty",
>                 "supplier.s_suppkey"
>             ],
>             "Plans": [
>                 {
>                     "Node Type": "Hash Join",
>                     "Parent Relationship": "Outer",
>                     "Parallel Aware": false,
>                     "Join Type": "Inner",
>                     "Startup Cost": 1073.99,
>                     "Total Cost": 19690.09,
>                     "Plan Rows": 16627,
>                     "Plan Width": 8,
>                     "Inner Unique": true,
>                     "Hash Cond": "(partsupp.ps_suppkey = supplier.s_suppkey)",
>                     "Plans": [
>                         {
>                             "Node Type": "Bitmap Heap Scan",
>                             "Parent Relationship": "Outer",
>                             "Parallel Aware": false,
>                             "Relation Name": "partsupp",
>                             "Alias": "partsupp",
>                             "Startup Cost": 601.54,
>                             "Total Cost": 19145.3,
>                             "Plan Rows": 27547,
>                             "Plan Width": 8,
>                             "Recheck Cond": "(ps_supplycost > 965.06)",
>                             "Plans": [
>                                 {
>                                     "Node Type": "Bitmap Index Scan",
>                                     "Parent Relationship": "Outer",
>                                     "Parallel Aware": false,
>                                     "Index Name": "<13002>btree_partsupp_ps_supplycost",
>                                     "Startup Cost": 0,
>                                     "Total Cost": 594.65,
>                                     "Plan Rows": 27547,
>                                     "Plan Width": 0,
>                                     "Index Cond": "(ps_supplycost > 965.06)"
>                                 }
>                             ]
>                         },
>                         {
>                             "Node Type": "Hash",
>                             "Parent Relationship": "Inner",
>                             "Parallel Aware": false,
>                             "Startup Cost": 397,
>                             "Total Cost": 397,
>                             "Plan Rows": 6036,
>                             "Plan Width": 4,
>                             "Plans": [
>                                 {
>                                     "Node Type": "Seq Scan",
>                                     "Parent Relationship": "Outer",
>                                     "Parallel Aware": false,
>                                     "Relation Name": "supplier",
>                                     "Alias": "supplier",
>                                     "Startup Cost": 0,
>                                     "Total Cost": 397,
>                                     "Plan Rows": 6036,
>                                     "Plan Width": 4,
>                                     "Filter": "((s_nationkey < 23) AND ((s_address)::text <> '2MJl7GcaHrJA4FEUxarCld9Feht7otlkleD2Bc'::text) AND (s_phone <= '26-432-258-4986'::bpchar))"
>                                 }
>                             ]
>                         }
>                     ]
>                 }
>             ]
>         }
>     }
> ]
> ```

**Comment by chenjifei111222** [comment]
Thank you for your answer. Can you please send me the dataset you are using? What is the difference between w/o and w/  here?

**Comment by Beliefuture** [comment]
@chenjifei111222 Hi! The difference between `w/o` and `w/` is that the `w/o` corresponds to the query plan without the usage of any index and the `w/` corresponds to the query plan with the usage of the indexes in `indexes`.
